name: kinshasa
description: A drink recipe app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # c
  cupertino_icons: ^1.0.4
  carousel_slider: ^4.0.0

  # d
  draggable_scrollbar: ^0.1.0

  # f
  flutter_bounce: ^1.1.0
  flutter_email_sender: ^5.0.2

  # g
  get: ^4.6.1

  # i
  intl: ^0.17.0

  # l
  line_awesome_icons: ^1.0.4+2

  # p
  path: ^1.8.0
  path_provider: ^2.0.8

  # s
  sqflite: ^2.0.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/DRINKS.db
    - assets/images/juice_images/
    - assets/images/smoothie_images/
    - assets/images/shake_images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
