name: kinshasa
description: A drink recipe app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # c
  cupertino_icons: ^1.0.4
  carousel_slider: ^4.0.0

  # d
  draggable_scrollbar: ^0.1.0

  # f
  flutter_bounce: ^1.1.0
  flutter_emoji: ^2.2.1+1
  flutter_beautiful_popup: ^1.7.0
  flutter_email_sender: ^5.0.2

  # g
  get: ^4.6.1

  # i
  intl: ^0.17.0

  # l
  line_awesome_icons: ^1.0.4+2

  # p
  path: ^1.8.0
  path_provider: ^2.0.8
  provider: ^6.0.2

  # s
  sqflite: ^2.0.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/DRINKS.db
    - assets/images/juice_images/
    - assets/images/smoothie_images/
    - assets/images/shake_images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
